version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: production
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      DB_HOST: db
      DB_USER: mail
      DB_PASS: admin
      DB_NAME: automail
    depends_on:
      - db
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: automail
      MYSQL_USER: mail
      MYSQL_PASSWORD: admin
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
